"""make job_id nullable in screening_results

Revision ID: b124d39b4905
Revises: a1ce1075aaa0
Create Date: 2026-09-02 12:18:29.805378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b124d39b4905'
down_revision: Union[str, None] = 'a1ce1075aaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screening_results', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screening_results', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
